### ISSUE TITLE
Trap getting punishment

### ISSUE THREAD

**Issue by ioull** [bdbogjoe/pronote-rest#10]
When accessing /punishments

I got an error 500 :
```
{"error":{"code":500,"description":"","message":"","type":"ParsingError"},"success":false}
```

And in the logs I got
```
2024-10-04 10:07:37,483 - pronote-rest - ERROR - Could not follow path
2024-10-04 10:07:37,483 - pronote-rest - ERROR - Could not follow path
Traceback (most recent call last):
  File "/home/app/.local/lib/python3.12/site-packages/pronotepy/dataClasses.py", line 220, in __call__
    json_value = json_value[p]
                 ~~~~~~~~~~^^^
KeyError: 'travailAFaire'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/app/.local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/app.py", line 310, in data_period
    if hasattr(p, type):
       ^^^^^^^^^^^^^^^^
  File "/home/app/.local/lib/python3.12/site-packages/pronotepy/dataClasses.py", line 641, in punishments
    return [Punishment(self._client, a) for a in absences if a["G"] == 41]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.local/lib/python3.12/site-packages/pronotepy/dataClasses.py", line 2074, in __init__
    self.homework: str = self._resolver(str, "travailAFaire")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.local/lib/python3.12/site-packages/pronotepy/dataClasses.py", line 234, in __call__
    raise ParsingError(
pronotepy.exceptions.ParsingError: Could not follow path
2024-10-04 10:07:37,484 - werkzeug - INFO - 172.19.0.10 - - [04/Oct/2024 10:07:37] "GET /punishments HTTP/1.1" 500 -
```

**Comment by bdbogjoe** [comment]
linked to : https://github.com/bain3/pronotepy/issues/312
